=== Arth19/AcademiaMule2021_Arthur/src/main/resources/api/schemas/updateClothesRequest.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "id da roupa"
    },
    "name": {
      "type": "string",
      "description": "name da roupa"
    },
    "marca": {
      "type": "string",
      "description": "cor da roupa"
    },
    "cor": {
      "type": "string",
      "description": "cor da roupa"
    },
    "tamanho": {
      "type": "string",
      "description": "tamanho da roupa"
    },
    "dataEfetivado": {
      "type": "string",
      "description": "dataEfetivado da roupa"
    },
    "quantidade": {
      "type": "integer",
      "description": "quantidade da roupa"
    },
    "preco": {
      "type": "number",
      "description": "preco da roupa"
    },
    "outrasCores": {
      "type": "boolean",
      "description": "outrasCores da roupa"
    }
  },
  "required": [
    "id",
    "name",
    "marca",
    "cor",
    "tamanho",
    "dataEfetivado",
    "quantidade",
    "preco",
    "outrasCores"
  ]
}

=== Arth19/AcademiaMule2021_Arthur/src/main/resources/api/examples/queryAllClothes.json
[
  {
    "id":"2f4d2fbb00",
    "name": "Camisa do Hulk",
    "marca": "Hering",
    "cor": "Verde",
    "tamanho": "M",
    "dataEfetivado": "15/12/2020",
    "quantidade": 500,
    "preco": 22.5,
    "outrasCores": true
  },
  {
    "id":"48b793f3d5",
    "name": "Camisa do Capit√£o America",
    "marca": "Calvin Klein",
    "cor": "Vermelho",
    "tamanho": "P",
    "dataEfetivado": "15/12/2020",
    "quantidade": 200,
    "preco": 23.5,
    "outrasCores": true
  },
  {
    "id":"bad5536cdf",
    "name": "Camisa do Homem de Ferro",
    "marca": "Calvin Klein",
    "cor": "Amarela",
    "tamanho": "G",
    "dataEfetivado": "15/12/2020",
    "quantidade": 200,
    "preco": 33.5,
    "outrasCores": false              
  },
  {
    "id":"72ad1a7cb463",
    "name": "Camisa do Batman",
    "marca": "DC",
    "cor": "Preta",
    "tamanho": "XG",
    "dataEfetivado": "15/12/2020",
    "quantidade": 1000,
    "preco": 43.5,    
    "outrasCores": false
  },
  {
    "id":"7d8b0707e3db",
    "name": "Camisa da Mulher Maravilha",
    "marca": "DC",
    "cor": "Azul",
    "tamanho": "GG",
    "dataEfetivado": "15/12/2020",
    "quantidade": 200,
    "preco": 63.5,
    "outrasCores": false
  }
]
